description: Prepares the repo for a typical CI job

name: Prepare
runs:
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v6
      with:
        cache: pnpm
        node-version-file: ".nvmrc"

    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
